import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <p>
        Next JS App 
      </p>
        {children}
      </body>
    </html> 
  );
}


//  this is the main entry points of our application




import localFont from "next/font/local"; // Importing the localFont function from next/font/local to load custom fonts.
import "./globals.css"; // Importing the global stylesheet for the entire application.

const geistSans = localFont({
  src: "./fonts/GeistVF.woff", // Loading the GeistVF font from a local file.
  variable: "--font-geist-sans", // Defining a custom CSS variable for the font to be used in the app.
  weight: "100 900", // Specifying the range of font weights available for this font.
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff", // Loading the GeistMonoVF font from a local file.
  variable: "--font-geist-mono", // Defining a custom CSS variable for the font to be used in the app.
  weight: "100 900", // Specifying the range of font weights available for this font.
});

export const metadata = {
  title: "Create Next App", // Metadata for the app, specifying the title.
  description: "Generated by create next app", // Metadata for the app, specifying the description.
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"> {/* Setting the language attribute to English */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} 
        {/* Applying the custom font variables and ensuring text is rendered with anti-aliasing */}
      >
        <p>
          Next JS App {/* A simple text element for the app title or description */}
        </p>
        {children} {/* Rendering any child components passed to this layout */}
      </body>
    </html> 
  );
}

// This file is the main entry point of the Next.js application.
// It sets up global styles, fonts, and metadata, and provides the root layout structure for the entire app.
